web/router.ex
defmodule Jabba.Router do
  use Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Jabba do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/register", RegisterController, :new
    post "/register", RegisterController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", Jabba do
  #   pipe_through :api
  # end
end

lib/jabba/endpoint.ex
defmodule Jabba.Endpoint do
  use Phoenix.Endpoint, otp_app: :jabba

  # Serve at "/" the given assets from "priv/static" directory
  plug Plug.Static,
    at: "/", from: :jabba,
    only: ~w(css images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_jabba_key",
    signing_salt: "c4tRdE3i",
    encryption_salt: "v/dY4+P5"

  plug :router, Jabba.Router
end

lib/jabba/repo.ex
defmodule Jabba.Repo do
  use Ecto.Repo, otp_app: :jabba
end

web/models/user.ex
defmodule Jabba.User do
  use Jabba.Web, :model

  schema "users" do
    field :username
    field :name
    field :email
    field :password
  end

  @required_fields ~w(username name email password)

  def new do
    cast(%__MODULE__{}, nil, @required_fields)
  end

  def new(params) do
    cast(%__MODULE__{}, params, @required_fields)
    |> update_change(:name, &format_name/1)
    |> update_change(:username, &String.downcase/1)
    |> update_change(:email, &String.downcase/1)
    |> validate_length(:username, min: 1)
    |> validate_length(:name, min: 1)
    |> validate_format(:email, ~r/@/)
    |> validate_length(:password, min: 8)
    |> validate_unique_user()
  end

  def create(%{changes: user}) do
    :ejabberd_auth.try_register(user.username, host, user.password)
    setup_vcard(user)
  end

  defp setup_vcard(user) do
    :mod_admin_extra.set_nickname(user.username, host, user.username)
    :mod_admin_extra.set_vcard(user.username, host, "FN", user.name)
    :mod_admin_extra.set_vcard(user.username, host, "EMAIL", "USERID", user.email)
  end

  defp format_name(name) do
    Enum.map_join(String.split(name), " ", &String.capitalize(&1))
  end

  defp validate_unique_user(%{changes: user} = changeset) do
    case :ejabberd_auth.is_user_exists(user.username, host) do
      true  -> add_error(changeset, :username, "already exists")
      false -> changeset
    end
  end
end

web/controllers/page_controller.ex
defmodule Jabba.PageController do
  use Jabba.Web, :controller

  plug :action

  def index(conn, _params) do
    users = :ejabberd_admin.registered_users(host)
    render conn, "index.html", users: users
  end
end

web/controllers/register_controller.ex
defmodule Jabba.RegisterController do
  use Jabba.Web, :controller

  alias Jabba.User

  plug :action

  def new(conn, _params) do
    user = User.new
    render conn, "new.html", user: user
  end

  def create(conn, %{"user" => params}) do
    user = User.new(params)
    if user.valid? do
      User.create(user)
      conn
      |> put_flash(:info, "Registered successfully!")
      |> redirect(to: page_path(conn, :index))
    else
      render conn, "new.html", user: user
    end
  end
end

web/views/error_view.ex
defmodule Jabba.ErrorView do
  use Jabba.Web, :view

  def render("404.html", _assigns) do
    "Page not found - 404"
  end

  def render("500.html", _assigns) do
    "Server internal error - 500"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Jabba.LayoutView do
  use Jabba.Web, :view
end

web/views/page_view.ex
defmodule Jabba.PageView do
  use Jabba.Web, :view
end

web/views/register_view.ex
defmodule Jabba.RegisterView do
  use Jabba.Web, :view
end

web/templates/layout/application.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Phoenix!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
        </ul>
        <span class="logo"></span>
      </div>

      <p class="alert alert-info"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger"><%= get_flash(@conn, :error) %></p>

      <%= @inner %>

      <div class="footer">
        <p><a href="http://phoenixframework.org">phoenixframework.org</a></p>
      </div>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>require("web/static/js/app")</script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2>ejabberd Users</h2>
  <p class="lead">Phoenix is an Elixir Web Framework targeting full-featured, fault tolerant applications with realtime functionality.</p>
  <ul>
    <%= for user <- @users do %>
    <li><%= user %></li>
    <% end %>
  </ul>
</div>

web/templates/register/new.html.eex
<h2>Register</h2>

<%= form_for @user, register_path(@conn, :create), fn f -> %>
  <%= if f.errors != [] do %>
    <div class="alert alert-danger">
      <p>
        <strong>Whoops! Something went wrong.</strong><br>
        <ul>
          <%= for {attr, msg} <- f.errors do %>
          <li><%= humanize(attr) %> <%= msg %>
          <% end %>
        </ul>
      </p>

    </div>
  <% end %>

  <div class="form-group">
    <%= text_input f, :username, class: "form-control input-lg", placeholder: "Username" %>
  </div>
  <div class="form-group">
    <%= text_input f, :name, class: "form-control input-lg", placeholder: "Name" %>
  </div>
  <div class="form-group">
    <%= text_input f, :email, class: "form-control input-lg", placeholder: "Email" %>
  </div>
  <div class="form-group">
    <%= password_input f, :password, class: "form-control input-lg", placeholder: "Password" %>
  </div>
  <%= submit "Register!", class: "btn btn-primary btn-lg btn-block" %>
<% end %>